# Generated by Django 5.1.3 on 2024-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_medicine_oriprice_alter_medicine_discprice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("doctor", "Doctor")],
                default="doctor",
                max_length=10,
            ),
        ),
    ]
