# Generated by Django 5.1.3 on 2024-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="medicine_images/"
            ),
        ),
    ]
